Edits branch
Benjamin-Lee/deep-rules pull request #263
Opened 2020-10-11 23:44 UTC by betsig

**Did you add yourself as a [contributor](https://github.com/Benjamin-Lee/deep-rules/blob/master/contributors.md) if this is your first contribution?**

- [x] Yes, I added myself or am already a contributor

**Any more details?**
For https://github.com/Benjamin-Lee/deep-rules/issues/260

2020-10-12 01:06 UTC, Benjamin-Lee approved these changes

2020-10-12 01:20 UTC, Benjamin-Lee requested changes
Can you update these fixes to close #260?

2020-10-13 02:00 UTC, Benjamin-Lee approved these changes

2020-10-13 02:22 UTC, rasbt approved these changes
Was just looking into the expansions of the abbreviations, and these look good to me.

2020-10-13 02:50 UTC, merged